### ISSUE TITLE
Reset Font Size broken on Obsidian v0.14.6 desktop

### ISSUE THREAD

**Issue by codyburleson** [luckman212/obsidian-reset-font-size#2]
When I click the button to reset font size, it no longer works. Following is the console error that appears now on the action:

```js
Uncaught TypeError: this.app.changeBaseFontSize is not a function
    at ResetFontSizePlugin.doReset (eval at <anonymous> (app.js:1:1494667), <anonymous>:75:18)
    at HTMLDivElement.eval (eval at <anonymous> (app.js:1:1494667), <anonymous>:43:111)
```

**Comment by luckman212** [comment]
Hmm. I haven't tested this much with recent builds, I'll take a look ASAP.

**Comment by luckman212** [comment]
@codyburleson Please try with this version, hopefully it works for you!

**Comment by codyburleson** [comment]
Confirmed; It works. Thank you so much!
